version: "3.3"
services:
  #------------------------------------------------------------------------
  exchange-service:
    build: ./
    image: test/exchange-service
    container_name: exchage-service
    ports:
      - 8080:8080
      - 25101:5105
    links:
      - exchange-service-postgres
    environment:
      DB_HOST: exchange-service-postgres

  exchange-service-postgres:
    image: postgres
    container_name: exchange-service-postgres
    ports:
      - 25102:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1
      POSTGRES_DB: exchange
