server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:exchange}
    username: ${DB_USERNAME:user1}
    password: ${DB_PASSWORD:user1}
  jpa:
    generate-ddl: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,refresh
  endpoint:
    health:
      show-details: always

